#!/bin/bash

ctypes='300G ssd hydro'

mus='1 8 6 4 2'

mkdir -p onelog

rm -f ./onelog/*

for ctype in $ctypes; do

    for mu in $mus; do

        in=./atlas_180_300/G2V/matthias/$ctype/8/angles/lte/$mu/spec

        files=$(ls $in)

        for f in $files; do

            gr=$(grep -e E+[1-9][1-9] $in/$f)

            if [ "$gr" ]; then

                echo $in/$f

                echo $in/$f >> ./onelog/${ctype}_${mu}

#                grep -e E+[1-9][1-9] $in/$f

            fi

        done

    done

done
